apiVersion: v1
kind: Namespace
metadata:
  name: pilot-ns
  labels:
    name: pilot-ns
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: pilot-deployment
  namespace: pilot-ns
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: pilot-app
    spec:
      containers:
      - name: pilot
        image: cloud66/pilot:latest
        command: ["/go/src/app/app"]
        ports:
        - containerPort: 8050
---
apiVersion: v1
kind: Service
metadata:
  name: pilot-svc
  namespace: pilot-ns
  labels:
    app: pilot-app
spec:
  type: NodePort
  ports:
  - port: 8050  # intra-pod port
    targetPort: 8050 # port inside container
    protocol: TCP
    nodePort: 30001 # port on service (exposed)
    name: http
  selector:
    app: pilot-app
